start_jobs: Do not rely on folder structure as strongly

diff --git a/ggpeps/tools/start_jobs b/ggpeps/tools/start_jobs
--- a/ggpeps/tools/start_jobs
+++ b/ggpeps/tools/start_jobs
@@ -3,8 +3,13 @@ set -eu
 
 for x in $@
 do
-	cd $x
-	echo "Starting $x"
-	sbatch slurmjob
-	cd ..
+  if [[ -d $x ]]
+  then
+    cd $x
+    echo "Starting $x"
+    sbatch slurmjob
+    cd ..
+  else
+    echo >&2 "ERROR: $x is not a directory. Skipping"
+  fi
 done
